name: tuf-on-ci repository test examples

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions: {}

jobs:
  test-oncall-prober:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with reasonable reference times
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://tuf-repo-cdn.sigstage.dev/
          metadata_dir: dedup_dir
          compare_source: false
          valid_days: 2
          offline_valid_days: 15

      - name: Pretend deduplication step
        run: |
          ls -l dedup_dir
          echo "Dedup key is:"
          sha256sum dedup_dir/* | sha256sum | cut -d " " -f 1

  test-oncall-prober-with-initial-root:
    runs-on: ubuntu-latest
    steps:
      - name: fetch initial root
        run: curl -o root.json https://tuf-repo-cdn.sigstore.dev/5.root.json

      - name: repository test with a repo that has incompatible metadata before root v5
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://tuf-repo-cdn.sigstore.dev/
          metadata_dir: dedup_dir
          compare_source: false
          valid_days: 2
          offline_valid_days: 15

      - name: Pretend deduplication step
        run: |
          ls -l dedup_dir
          echo "Dedup key is:"
          sha256sum dedup_dir/* | sha256sum | cut -d " " -f 1

  test-upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with upgrade test
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://sigstore.github.io/root-signing-staging/
          update_base_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 2
          offline_valid_days: 15

  test-expect-fail-on-call-prober:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with unreasonable reference time
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 16
          offline_valid_days: 15

  test-expect-fail-on-call-prober2:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with unreasonable reference time
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 2
          offline_valid_days: 200
