name: root-signing GCS repository tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions: {}

jobs:
  test-oncall-prober:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with reasonable reference times
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://tuf-repo-cdn.sigstage.dev/
          metadata_dir: dedup_dir
          compare_source: false
          valid_days: 2
          offline_valid_days: 15

      - name: Pretend deduplication step
        run: |
          ls -l dedup_dir
          echo "Dedup key is:"
          sh256sum dedup_dir/* | sha256sum | cut -d " " -f 1

  test-upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with upgrade test
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://https://sigstore.github.io/root-signing-staging/
          update_base_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 2
          offline_valid_days: 15

  test-expect-fail:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with unreasonable reference time
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://https://sigstore.github.io/root-signing-staging/
          update_base_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 16

  test-expect-fail2:
    runs-on: ubuntu-latest
    steps:
      - name: repository test with unreasonable reference time
        uses: jku/tuf-on-ci/actions/test-repository@test-repository-improvements
        with:
          metadata_url: https://https://sigstore.github.io/root-signing-staging/
          update_base_url: https://tuf-repo-cdn.sigstage.dev/
          compare_source: false
          valid_days: 2
          offline_valid_days: 200
